spring:
  devtools:
    restart:
      enabled: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/clockbot?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&useTimezone=true&serverTimezone=GMT%2B8&allowMultiQueries=true
    username: root
    password: root@Liu332331
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
# mybatis
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    org.example.bot.accountBot.mapper: debug
  pattern:
    console: '%d{YYYY-MM-dd HH:mm:ss.SSS} %clr(%-5level) --- [%-15thread]%cyan(%-50logger{50}):%msg%n'
#这个是超级管理员 可以私聊别人设置管理员权限
adminUserId: 6976772117
vueUrl: http://www.yaoke.cc/
#每隔一分钟检查一次
scheduler:
  fixed-rate: 10000
telegram:
  bot:
    token: 6796265375:AAFidGpg5xGJpcmC9sx78bvGknd1HtkyGKU
    username: Fvipbot
