server:
  port: 8081

spring:
  profiles:
    active: test
    #  ssl:
    #    enabled: true
    #    key-store-type: JKS
    #    key-store: classpath:server.jks
    #    key-store-password: 123456
    #    protocol: TLS
    #    key-alias: server