spring:
  devtools:
    restart:
      enabled: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bot?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&useTimezone=true&serverTimezone=GMT%2B8&allowMultiQueries=true
    username: root
    password: root
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
# mybatis??
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    org.example.bot.accountBot.mapper: debug
  pattern:
    console: '%d{YYYY-MM-dd HH:mm:ss.SSS} %clr(%-5level) --- [%-15thread]%cyan(%-50logger{50}):%msg%n'
botUserId: 7203617407   #我机器人的id
vueUrl: http://192.168.0.9:8080/
Origin: http://43.128.113.117:8081
Origin1: http://www.yaoke.cc
Origin2: http://www.yaoke.cc:8081
apiKey: 2967e678-556e-497a-a892-a1dcee897ba5
apiKey1: a7089da7-e17b-4d28-a3d3-29f799983cae
apiKey2: e9b66829-5dde-4f5e-9611-37bc9f26f4c7
#获取最新汇率
tranAccountUrl: https://apilist.tronscanapi.com/api/accountv2?address=
#tranAccountUrl: https://apilist.tronscan.org/api/account?address=  备用地址
tranHistoryUrl: https://apilist.tronscanapi.com/api/filter/trc20/transfers?limit=10&start=0&sort=-timestamp&count=true&filterTokenValue=0&relatedAddress=
uploadFileGangbo: D://
telegram:
  bot:
    #测试
#    token: 7532424117:AAEieNRdj5lBvwUoEZbPV_CHKKvbbYv6uow
#    username: ftfgg6543366bot
    #正式环境
#    token: 6736457256:AAHo8BBhs9E3hIG4xBkiAiZEYnVCcNoEKDM
#    username: Evipbot
    #个人
    token: 7203617407:AAGq9fe9aZSEanFkOa3oa219bEnJI_4RKY4
    username: my_niu_bot
